apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: mongo-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: ibmc-file-gold-gid
  volumeMode: Filesystem
